#!/usr/bin/env bash

source "$T2_SCRIPTS/helpers/colours.sh"
source "$T2_SCRIPTS/helpers/script_requires_project_name_as_param.sh"
source "$T2_SCRIPTS/helpers/requiresPackagesOrModules.sh"

# if empty, default to packages
if [[ -z "$2" ]]; then
    AG_GRID_METHOD='packages'
fi
# to lowercase
PROJECT_NAME=$(echo "$1" | tr '[:upper:]' '[:lower:]')
NEW_PROJECT_DIR_PATH="$T2_HOME/projects/$PROJECT_NAME"
CACHED_PROJECT_DIR_PATH="$T2_HOME/cache/$AG_GRID_METHOD/cached-$FRAMEWORK"

# if cached framework project does not exist, exit process
if [[ ! -d $CACHED_PROJECT_DIR_PATH ]]; then
    echo -e "${RED}Cache does not exist for $AG_GRID_METHOD/cached-$FRAMEWORK.\nPlease run:\n  ${GREEN}t2-update-cache -$FRAMEWORK --$AG_GRID_METHOD"
    exit 1
fi

# if project already exists, exit process
if [[ -d $NEW_PROJECT_DIR_PATH ]]; then
    echo "$PROJECT_NAME already exists in projects"
    exit 1
fi

echo -e "Creating ${GREEN}$FRAMEWORK ${NOCOLOR}project with AG Grid ${GREEN}$AG_GRID_METHOD ${CYAN}[$PROJECT_NAME]${NOCOLOR}..."

# move project contents from t2/cache into t2/projects folder
mkdir $NEW_PROJECT_DIR_PATH
mv $CACHED_PROJECT_DIR_PATH/* $NEW_PROJECT_DIR_PATH/

# update ag-grid.config file
gsed -i "s/TICKET=.*/TICKET=\"$PROJECT_NAME\"/" $NEW_PROJECT_DIR_PATH/ag-grid.config.sh

# https://fsymbols.com/generators/carty/
# https://fsymbols.com/text-art/
echo -e "${GREEN}"
echo -e "░██████╗░██████╗░██╗██████╗░  ██████╗░███████╗░█████╗░██████╗░██╗░░░██╗"
echo -e "██╔════╝░██╔══██╗██║██╔══██╗  ██╔══██╗██╔════╝██╔══██╗██╔══██╗╚██╗░██╔╝"
echo -e "██║░░██╗░██████╔╝██║██║░░██║  ██████╔╝█████╗░░███████║██║░░██║░╚████╔╝░"
echo -e "██║░░╚██╗██╔══██╗██║██║░░██║  ██╔══██╗██╔══╝░░██╔══██║██║░░██║░░╚██╔╝░░"
echo -e "╚██████╔╝██║░░██║██║██████╔╝  ██║░░██║███████╗██║░░██║██████╔╝░░░██║░░░"
echo -e "░╚═════╝░╚═╝░░╚═╝╚═╝╚═════╝░  ╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝╚═════╝░░░░╚═╝░░░"
echo -e "${NOCOLOR}"
echo -e "Project created at: $NEW_PROJECT_DIR_PATH"

if [ -n $MY_EDITOR ]; then
    # open in text editor
    $MY_EDITOR $NEW_PROJECT_DIR_PATH
fi

# update cache in foreground
source "$T2_SCRIPTS/t2-update-cache" -$FRAMEWORK --$AG_GRID_METHOD
