#!/usr/bin/env bash

source "$T2_SCRIPTS/helpers/colours.sh"
source "scripts/helpers/script_requires_project_name_as_param.sh"
cd $T2_HOME

PROJECT_NAME=$(echo "$1" | tr '[:upper:]' '[:lower:]')
AG_GRID_METHOD='packages'
NEW_PROJECT_DIR_PATH="$T2_HOME/projects/$PROJECT_NAME"

if [[ $2 = "--modules" ]]; then
    AG_GRID_METHOD='modules'
fi

if [[ $AG_GRID_METHOD == "modules" ]]; then
    echo -e "Creating ${GREEN}$FRAMEWORK ${NOCOLOR}project with AG Grid ${GREEN}Modules ${CYAN}[$PROJECT_NAME]${NOCOLOR}..."
    CACHED_PROJECT_DIR_PATH="$T2_HOME/cache/modules/cached-$FRAMEWORK"
else
    echo -e "Creating ${GREEN}$FRAMEWORK ${NOCOLOR}project with AG Grid ${GREEN}Packages ${CYAN}[$PROJECT_NAME]${NOCOLOR}..."
    CACHED_PROJECT_DIR_PATH="$T2_HOME/cache/packages/cached-$FRAMEWORK"
fi

# to lowercase

# move project contents from t2/cache into t2/projects folder
mkdir $NEW_PROJECT_DIR_PATH
mv $CACHED_PROJECT_DIR_PATH/* $NEW_PROJECT_DIR_PATH/

# update ag-grid.config file
gsed -i "s/TICKET=.*/TICKET=\"$PROJECT_NAME\"/" $NEW_PROJECT_DIR_PATH/ag-grid.config.sh

# https://fsymbols.com/generators/carty/
# https://fsymbols.com/text-art/
echo ""
echo -e "${GREEN}░██████╗░██████╗░██╗██████╗░  ██████╗░███████╗░█████╗░██████╗░██╗░░░██╗"
echo -e "██╔════╝░██╔══██╗██║██╔══██╗  ██╔══██╗██╔════╝██╔══██╗██╔══██╗╚██╗░██╔╝"
echo -e "██║░░██╗░██████╔╝██║██║░░██║  ██████╔╝█████╗░░███████║██║░░██║░╚████╔╝░"
echo -e "██║░░╚██╗██╔══██╗██║██║░░██║  ██╔══██╗██╔══╝░░██╔══██║██║░░██║░░╚██╔╝░░"
echo -e "╚██████╔╝██║░░██║██║██████╔╝  ██║░░██║███████╗██║░░██║██████╔╝░░░██║░░░"
echo -e "░╚═════╝░╚═╝░░╚═╝╚═╝╚═════╝░  ╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝╚═════╝░░░░╚═╝░░░${NOCOLOR}"
echo -e ""
echo -e "Project created at: $NEW_PROJECT_DIR_PATH"
echo ""

if [ -n $MY_EDITOR ]; then
    # open in text editor
    $MY_EDITOR $NEW_PROJECT_DIR_PATH
fi

# update cache in foreground
source "scripts/t2-update-cache" -$FRAMEWORK --$AG_GRID_METHOD
