export const columnDefs = [
  {
    enablePivot: true,
    enableRowGroup: true,
    enableValue: false,
    pivot: false,
    rowGroup: false,
    field: "9344f567a",
    colId: "9344f567a",
    headerName: "9344f567a",
    cellRendererParams: { initialColId: "9344f567a" },
    type: "",
    filter: "agMultiColumnFilter",
    filterParams: {
      filters: [
        {
          filter: "agTextColumnFilter",
          filterParams: { buttons: ["clear"] },
        },
        { filter: "agSetColumnFilter" },
      ],
    },
  },
  {
    enablePivot: true,
    enableRowGroup: true,
    enableValue: false,
    pivot: false,
    rowGroup: false,
    field: "476708c68",
    colId: "476708c68",
    headerName: "476708c68",
    cellRendererParams: { initialColId: "476708c68" },
    type: "",
    filter: "agMultiColumnFilter",
    filterParams: {
      filters: [
        {
          filter: "agTextColumnFilter",
          filterParams: { buttons: ["clear"] },
        },
        { filter: "agSetColumnFilter" },
      ],
    },
  },
  {
    enablePivot: true,
    enableRowGroup: true,
    enableValue: false,
    pivot: false,
    rowGroup: false,
    field: "5e717fb048c0",
    colId: "5e717fb048c0",
    headerName: "5e717fb048c0",
    cellRendererParams: { initialColId: "5e717fb048c0" },
    type: ["TENOR"],
    filter: "agMultiColumnFilter",
    filterParams: {
      filters: [
        {
          filter: "agTextColumnFilter",
          filterParams: { buttons: ["clear"] },
        },
        { filter: "agSetColumnFilter" },
      ],
    },
  },
  {
    enablePivot: true,
    enableRowGroup: true,
    enableValue: false,
    pivot: false,
    rowGroup: false,
    field: "eabef5ab7daa49",
    colId: "eabef5ab7daa49",
    headerName: "eabef5ab7daa49",
    cellRendererParams: { initialColId: "eabef5ab7daa49" },
    type: "",
    filter: "agMultiColumnFilter",
    filterParams: {
      filters: [
        {
          filter: "agTextColumnFilter",
          filterParams: { buttons: ["clear"] },
        },
        { filter: "agSetColumnFilter" },
      ],
    },
  },
  {
    enablePivot: true,
    enableRowGroup: true,
    enableValue: false,
    pivot: false,
    rowGroup: false,
    field: "5ed39639",
    colId: "5ed39639",
    headerName: "5ed39639",
    cellRendererParams: { initialColId: "5ed39639" },
    type: "",
    filter: "agMultiColumnFilter",
    filterParams: {
      filters: [
        {
          filter: "agTextColumnFilter",
          filterParams: { buttons: ["clear"] },
        },
        { filter: "agSetColumnFilter" },
      ],
    },
  },
  {
    allowedAggFuncs: ["sum", "min", "max", "count", "avg", "first", "last"],
    aggFunc: "sum",
    enablePivot: false,
    enableRowGroup: false,
    enableValue: true,
    pivot: false,
    rowGroup: false,
    field: "80fdcd29782b4f808f744175",
    colId: "80fdcd29782b4f808f744175",
    headerName: "80fdcd29782b4f808f744175",
    cellRendererParams: { initialColId: "80fdcd29782b4f808f744175" },
    type: ["numericColumn", "NUMBER"],
    filter: "agNumberColumnFilter",
    filterParams: { buttons: ["clear"] },
    enableCellChangeFlash: true,
  },
];
