export const columnState = [
    {
      colId: "ag-Grid-AutoColumn",
      aggFunc: null,
      pivot: false,
      pivotIndex: null,
      rowGroup: false,
      rowGroupIndex: null,
      hide: false,
      width: 200,
      pinned: null,
      sort: null,
      sortIndex: null,
      flex: null,
    },
    {
      colId: "5ed39639",
      aggFunc: null,
      pivot: false,
      pivotIndex: null,
      rowGroup: true,
      rowGroupIndex: 0,
      hide: true,
      header: "5ed39639",
      columnIndex: null,
      column: false,
      sort: null,
      sortIndex: null,
    },
    {
      colId: "476708c68",
      aggFunc: null,
      pivot: false,
      pivotIndex: null,
      rowGroup: true,
      rowGroupIndex: 1,
      hide: true,
      header: "476708c68",
      columnIndex: null,
      column: false,
      sort: null,
      sortIndex: null,
    },
    {
      colId: "5e717fb048c0",
      aggFunc: null,
      pivot: true,
      pivotIndex: 0,
      rowGroup: false,
      rowGroupIndex: null,
      hide: false,
      header: "5e717fb048c0",
      columnIndex: null,
      column: false,
      sort: null,
      sortIndex: null,
    },
    {
      colId: "9344f567a",
      aggFunc: null,
      pivot: true,
      pivotIndex: 1,
      rowGroup: false,
      rowGroupIndex: null,
      hide: false,
      header: "9344f567a",
      columnIndex: null,
      column: false,
      sort: null,
      sortIndex: null,
    },
    {
      colId: "80fdcd29782b4f808f744175",
      aggFunc: "sum",
      pivot: false,
      pivotIndex: null,
      rowGroup: false,
      rowGroupIndex: null,
      hide: false,
      header: "rbpl",
      columnIndex: 0,
      column: true,
      sort: null,
      sortIndex: null,
    },
    {
      colId: "eabef5ab7daa49",
      aggFunc: null,
      pivot: false,
      pivotIndex: null,
      rowGroup: false,
      rowGroupIndex: null,
      hide: false,
      header: "eabef5ab7daa49",
      columnIndex: 1,
      column: true,
      sort: null,
      sortIndex: null,
    },
  ];
  