#!/usr/bin/env bash

T2_PROJECTS_DIR_PATH="$T2_HOME/projects"

# if running script from outside of our projects folder -> exit
if [[ $PWD != $T2_PROJECTS_DIR_PATH/** ]]; then
    echo "You must run this script from within a subdirectory inside $T2_PROJECTS"
    exit 1
fi

if [[ ! -f ag-grid.config.sh ]]; then
    echo "ag-grid.config.sh file is missing"
    exit 1
fi

source "./ag-grid.config.sh"
cd $T2_PROJECTS_DIR_PATH

# remove file completely
# rm -r "$T2_PROJECTS_DIR_PATH/$TICKET"

# or move to ~/.Trash
mv "$T2_PROJECTS_DIR_PATH/$TICKET" ~/.Trash