#!/usr/bin/env bash

cd $T2_HOME

source "scripts/helpers/script_requires_framework_as_param"

if [ -z $2 ] ; then
  echo 'you must pass the project name as the second paramater to this script'
  echo 'e.g. t2-get -react my-app'
  exit 1
fi

# to lowercase
PROJECT_NAME=$(echo "$2" | tr '[:upper:]' '[:lower:]')

echo "Creating [$FRAMEWORK] project [$PROJECT_NAME]..."

CACHED_PROJECT_DIR_PATH="$T2_HOME/cache/cached-$FRAMEWORK"
NEW_PROJECT_DIR_PATH="$T2_HOME/projects/$PROJECT_NAME"

# move project contents from t2/cache into t2/projects folder
mkdir $NEW_PROJECT_DIR_PATH
mv $CACHED_PROJECT_DIR_PATH/* $NEW_PROJECT_DIR_PATH/

# update ag-grid.config file
gsed -i "s/TICKET=.*/TICKET=\"$PROJECT_NAME\"/" $NEW_PROJECT_DIR_PATH/ag-grid.config.sh

# https://fsymbols.com/generators/carty/
# https://fsymbols.com/text-art/
echo ""
echo "░██████╗░██████╗░██╗██████╗░  ██████╗░███████╗░█████╗░██████╗░██╗░░░██╗"
echo "██╔════╝░██╔══██╗██║██╔══██╗  ██╔══██╗██╔════╝██╔══██╗██╔══██╗╚██╗░██╔╝"
echo "██║░░██╗░██████╔╝██║██║░░██║  ██████╔╝█████╗░░███████║██║░░██║░╚████╔╝░"
echo "██║░░╚██╗██╔══██╗██║██║░░██║  ██╔══██╗██╔══╝░░██╔══██║██║░░██║░░╚██╔╝░░"
echo "╚██████╔╝██║░░██║██║██████╔╝  ██║░░██║███████╗██║░░██║██████╔╝░░░██║░░░"
echo "░╚═════╝░╚═╝░░╚═╝╚═╝╚═════╝░  ╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝╚═════╝░░░░╚═╝░░░"
echo ""
echo "project created at: $NEW_PROJECT_DIR_PATH"
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""

if [ -n $MY_EDITOR ]; then
    # open in text editor
    $MY_EDITOR $NEW_PROJECT_DIR_PATH  
fi

# update cache in foreground
source "scripts/t2-update-cache" -$FRAMEWORK