#!/usr/bin/env bash

cd $T2_HOME

source "scripts/helpers/script_requires_framework_as_param"
source "scripts/helpers/requiresPackagesOrModules.sh"

# if empty, default to packages
if [[ -z "$2" ]]; then
    AG_GRID_METHOD='packages'
fi

echo "Updating /cache/$AG_GRID_METHOD/cached-$FRAMEWORK project..."

source "scripts/helpers/init-cache" -$FRAMEWORK $AG_GRID_METHOD